harness void mul(bit[4] bv1, bit[4] bv2, ref bit[4] ret) {
    ret = {0, 0, 0, 0};
    if (bv2[0] == 1) { ret = ret + bv1; } 
    if (bv2[1] == 1) { ret = ret + (bv1 << 1); } 
    if (bv2[2] == 1) { ret = ret + (bv1 << 2); } 
    if (bv2[3] == 1) { ret = ret + (bv1 << 3); }
}

harness void test() {
    bit[4] bv1 = {1, 1, 1, 0};
    bit[4] bv2 = {1, 1, 0, 0};
    bit[4] bv3;

    mul(bv1, bv2, bv3);

    bit[4] bv = ??;

    assert bv3 == bv;
}